.TH vulkaninfo 1 "2018-01-25"
.SH NAME
vulkaninfo \- show Vulkan information
.SH SYNOPSIS
.B vulkaninfo
.SH DESCRIPTION
The \fIvulkaninfo\fP program shows information about the supported Vulkan
capabilities. It lists not only device properties and features, but also
supported Vulkan layers and extensions.
.SH AUTHOR
vulkaninfo was originally written by LunarG, Inc.
.PP
This manual page was written by Andreas Boll <andreas.boll.dev@gmail.com>, for
the Debian project (but may be used by others).
